Added functionality to ignore .env # comments and EOL whitespace
kHRISl33t/runtime-env-cra pull request #6
Opened 2021-08-16 20:19 UTC by seanblonien

Valid .env file comments that start with #, so added functionality to ignore anything after that symbol
Also trimmed whitespace at end of line

Apparently [dontenv doesn't even have this feature](https://github.com/motdotla/dotenv/issues/524), but I figured couldn't hurt

2021-08-17 14:29 UTC, kHRISl33t requested changes
Nice touch to the package, good work, thank you! :)
One small comment about the style, otherwise it looks good.

2021-08-17 14:29 UTC, kHRISl33t commented on lib/generateConfig.js
> +  content.split('\n').map(l => l.split('#')[0].trim()).forEach((line) => {
Can you split these into multiple lines to make them more readable?

Something like:
```
content.split('\n')
   .map()
   .forEach()
```

2021-08-17 16:21 UTC, seanblonien commented
If someone needs an environment variable value with a "#" in it, this solution doesn't really allow for that, but I think that's fine and not a common use-case, and easily solvable by replacing a pre-defined character pattern (such as HASH and doing a `str.replace(/HASH/g, '#')` )  if someone truly needs that functionality

2021-08-23 14:14 UTC, seanblonien commented
@kHRISl33t any more feedback on this?

2021-08-23 14:17 UTC, kHRISl33t commented
@seanblonien will merge it later today (in a few hours), I just need to finish the docs for it :)
Sorry, I have been swamped with work lately in the last few days.

2021-08-23 20:00 UTC, merged